apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: cm9vdA==       # base64-encoded value of MARIADB_ROOT_PASSWORD=root
  MARIADB_DATABASE: Z2xwaWRibA==       # base64-encoded value of MARIADB_DATABASE=glpidb
  MARIADB_USER: Z2xwaV91c2Vy          # base64-encoded value of MARIADB_USER=glpi_user
  MARIADB_PASSWORD: Z2xwaQ==          # base64-encoded value of MARIADB_PASSWORD=glpi
